

message(STATUS "source/_.cmake included")


set(INCLUDE_DRAW2D_CAIRO TRUE)
set(INCLUDE_FREETYPE TRUE)
set(INCLUDE_IMAGING_FREEIMAGE TRUE)
set(INCLUDE_AUDIO FALSE)
set(INCLUDE_GPU_OPENGL TRUE)
set(HAS_AUDIO_SYSTEM FALSE)
set(HAS_APP_VERIWELL FALSE)




